name: Bluetooth Manager
version: "1.0.1"
slug: bluetooth_manager
description: Web-based GUI for managing Bluetooth connections
url: https://github.com/burhanyldz/bluetooth-actions
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: "ghcr.io/burhanyldz/{arch}-addon-bluetooth_manager"
init: false
host_network: true
privileged:
  - SYS_ADMIN
devices:
  - /dev/bus/usb
boot: auto
startup: application
options:
  log_level: info
  port: 8099
schema:
  log_level: list(debug|info|warning|error)
  port: port
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
webui: "http://[HOST]:[PORT:8099]"
panel_icon: mdi:bluetooth
